@baseUrl = http://localhost:3000
# GET
GET {{baseUrl}}/films
###

# GET
GET {{baseUrl}}/films?minDuration=140
###

# GET
GET {{baseUrl}}/films?like=in
###

# GET
GET {{baseUrl}}/films/4
###


# POST
POST {{baseUrl}}/films
Content-Type: application/json

{
  "title": "Interstellar",
  "director": "Christopher Nolan",
  "duration": 169,
  "budget": 165000000,
  "description": "Dans un futur proche où la Terre se meurt, un groupe d'explorateurs voyage à travers un trou de ver pour trouver un nouvel endroit où l'humanité pourra survivre.",
  "imageUrl": "https://example.com/images/interstellar-poster.jpg"
}

###

# PUT
PUT {{baseUrl}}/films
Content-Type: application/json

{
"id" : 4, 
"title": "Interstellar",
"director": "Cristopher Nolan",
"duration": 169,
"budget": 170000000
}
###

# PATCH
PATCH {{baseUrl}}/films/4
Content-Type: application/json

{
  "title" : "Alice in Wonderland",
  "director" : "Tim Burton",
  "description" : "Alice, une jeune fille curieuse, aperçoit un lapin blanc pressé qui consulte sa montre. Intriguée, elle le suit et tombe dans un terrier qui la mène dans un monde étrange et merveilleux",
  "budget" : 5000000
}
###

# DELETE
DELETE {{baseUrl}}/films/2
###